os:
  - linux
sudo: false
notifications:
  email: false
language: node_js
cache: npm
node_js:
  - "node"
  - "6"
install:
  - npm install
script:
  - npm run lint
  - npm run test
jobs:
  include:
    - stage: npm release
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
