version: 2.1

orbs:
  win: circleci/windows@2.4.0
  prodsec: snyk/prodsec-orb@1

filters_branches_ignore_main: &filters_branches_ignore_main
  filters:
    branches:
      ignore:
        - main

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: "18.19.1"
  working_directory: ~/snyk-nodejs-plugin

windows_defaults: &windows_defaults
  environment:
    npm_config_loglevel: silent
  executor:
    name: win/default

test_matrix: &test_matrix
  node_version: ['14.17.6', '16.13.2', '18.19.1']

commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm install
  install_node_npm:
    description: Install correct Node version
    parameters:
      node_version:
        type: string
        default: ""
    steps:
      - run:
          name: Install correct version of Node
          command: nvm install << parameters.node_version >>
      - run:
          name: Use correct version of Node
          command: nvm use << parameters.node_version >>
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version

jobs:
  security-scans:
    <<: *defaults
    resource_class: small
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test,dist
  lint:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - show_node_version
      - run:
          name: Run lint
          command: npm run lint

  test-windows:
    <<: *defaults
    <<: *windows_defaults
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - install_node_npm:
          node_version: << parameters.node_version >>
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  test-unix:
    <<: *defaults
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  release:
    <<: *defaults
    docker:
      - image: node:18
    steps:
      - checkout
      - install_deps
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Publish to GitHub
          command: npx semantic-release@21

workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
      - security-scans:
          name: Perform security scans for PRs
          context:
            - open_source-managed
      - lint:
          name: Lint
          context: nodejs-install
          node_version: "lts"
      - test-windows:
          matrix:
            alias: test-windows
            parameters:
              <<: *test_matrix
          name: Windows Tests for Node=<< matrix.node_version >>
          context: nodejs-install
          requires:
            - Lint
          <<: *filters_branches_ignore_main
      - test-unix:
          matrix:
            alias: test-unix
            parameters:
              <<: *test_matrix
          name: Unix Tests for Node=<< matrix.node_version >>
          context: nodejs-install
          requires:
            - Lint
          <<: *filters_branches_ignore_main
      - release:
          name: Release
          context: nodejs-lib-release
          requires:
            - Scan repository for secrets
            - Perform security scans for PRs
            - Lint
          filters:
            branches:
              only:
                - main